name: farmapp
description: A new Flutter project.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Updated Flutter SDK version

dependencies:
  intl: ^0.17.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/potato.jpg
    - assets/carrot.jpg
    - assets/tomato.jpg
    - assets/cucumber.jpg
    - assets/apple.jpg
    - assets/strawberry.jpg
    - assets/watermelon.jpg
    - assets/grapes.jpg
    - assets/lettuce.jpg
    - assets/banana.jpg
    - assets/fruits.jpg
    - assets/vegetables.jpg
    - assets/seeds.jpg
    - assets/saplings.jpg
    - assets/cereals.jpg
    - assets/pulses.jpg
    - assets/rice.jpg
    - assets/rose.jpg
    - assets/sunflower.jpg
    - assets/broccoli.jpg
    - assets/mushroom.jpg
    - assets/Lentils.jpg
    - assets/user.jpg
    - assets/farmer.jpg
    - assets/fmart.png